name: LWJGL Build - Linux x64

on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  GLFW_PARAMS: -DGLFW_LIBRARY_TYPE=SHARED -DGLFW_BUILD_EXAMPLES=OFF -DGLFW_BUILD_TESTS=OFF -DGLFW_BUILD_DOCS=OFF -DCMAKE_BUILD_TYPE=Release

jobs:
  linux-x64:
    name: Linux x64 (Arch Linux)
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 4
      - name: Install build dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y install cmake gcc g++
      - name: Install GLFW dependencies
        run: |
          sudo apt-get -y install \
            libxrandr-dev \
            libxinerama-dev \
            libxcursor-dev \
            libxi-dev \
            libxext-dev \
            libxkbcommon-dev \
            libwayland-dev \
            wayland-protocols
      - name: Configure build
        run: |
          cmake -B build \
            -DGLFW_BUILD_WAYLAND=ON \
            -DCMAKE_C_FLAGS:STRING="${CMAKE_C_FLAGS} -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0" \
            $GLFW_PARAMS
      - name: Build
        run: |
          cmake --build build --parallel
          strip build/src/libglfw.so
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: glfw-linux-x64
          path: build/src/libglfw.so
          retention-days: 30
